android.useAndroidX=true
android.newDsl=false
sdk.dir=/Users/aditya/Library/Android/sdk
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx3g


# Flow Neuroengine
FLOW_NEURO_BASE_URL=https://api.flowneuroengine.com
FLOW_NEURO_API_KEY=dummy_key
